<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
<style>
body
{
background-image: url("imageedit_2.jpg");
  background-size:"cover";
background-repeat: yes-repeat;
background-attachment:fixed
 
}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 12px;
}
.topnav a:hover {
  background-color: #ddd;
  color: black;
}
.topnav a.active {
  background-color: #04AA6D;
  color: white;
}

.myDiv1 {
  border: 3px outset black;
  background-color:DEB887;
  width: 880px;
  height: 40px;
  float:center;
  padding: 2px 50px 25px 20px;
  text-align: center;
}
.myDiv2 {
  border: 3px outset black;
  background-color:F5DEB3;
  width: 880px;
  height: 200px;
  float:center;
  padding: 2px 50px 25px 20px;
  text-align: center;
}
.myDiv3 {
  border: 3px outset black;
  background-color:	F5DEB3;
  width: 880px;
  height: 300px;
  float:center;
  padding: 2px 50px 25px 20px;
  text-align: center;
}
  .myDiv4 {
  border: 3px outset black;
  background-color:F5DEB3;
  width: 880px;
  height: 300px;
  float:center;
  padding: 2px 50px 25px 20px;
  text-align: justify;
  }
 </style>
</head>
<body>
<br>

<div class="topnav">
  <a class="active" href="Home.php">Home</a>
  <a href="About us.php">About us</a>
  <a href="Facilities.php">Facilties</a>
  <a href="Documentation.php">Documentation</a>
  <a  href="Application Form.php">Registration Form</a>
  <a href="Contact us.php">Contact Us</a>
</div><br>

<center>
<div class="myDiv1">
<b><h1><u><center><font color="maroon">***About us***</u></h1></b></center></font color>
</center>
<br>

<center>
<div class="myDiv2">
<b><h2><u><font color="maroon">About our School</h2></b></u></font color>
<p align="center"><h4>Gurudev Rabindranath Tagore described the Indian education system as," a machine that crushes the joy and freedom for which children have an insatiable thirst".
<br>
'All Saints High School' is an institution, which strives for providing children with quality education without compromising on their joy and freedom.<br>
The school is , a well-researched, well-organized educational project seeks to chart a new course in education, a world apart from the outmoded education system.</h4>
</center>
<br></div><center>

<div class="myDiv3">
<h2><b><center><u><font color="maroon">Profile</b></h2></u></font color>
<h4>Established in 2002, the All Saints High School extends commitment of quality education and a positive, proactive learning environment to the students.<br> This challenges and assists them to become competent, thoughtful, ethical and morally balanced citizens of a the global society.<br>
Name of Trust / Society / Company Registered under Section 25 of the Company Act, 1956, Period upto which Registration of Trust / Society is valid Shilpakar Education Society, which believes strongly in inculcating moral values within each student.
These values assist them in developing their cognitive abilities and capability to deal with the real world<br>
The school is located on about 21 acres, In Sq. mtrs – 101640, Built up area (sq.mtrs) 14450 of land with spacious infrastructure for academic as well as extra curricular activities. The infrastructure includes academic buildings, cricket and football grounds, 
Swimming pool, skating rink, tennis court , A.V. <br>theatre, campus clinic, Art, Dance and Music halls, Library and Science labs. The infrastructure facilities create a suitable ambience for the well being and potential growth of the students.
</h4></center>
<br></div><center>


<div class="myDiv4">
<h2><b><u><font color="Maroon"><center>Code of conduct</center></b></h2></u></font color>
All Saints High School maintains the code of conduct to preserve its dignity as a regulated institution. The code of conduct is laid down discretely for parents and resident students.
<br><b><center><u>Code of Conduct for Parents</center></b></u>
<ul type="disc">
<li>Parents must adhere to school rules at the time of visit.</li>
<li>Parents are supposed to sign an agreement and indemnity bond at the time of admission.</li>
<li>Fees must be paid in full if possible or in three installments well before stipulated date.</li>
<li>Either of the parents should be compulsorily present on an Open Day.</li>
<li>Sufficient financial help must be given to the child.</li>
<li>Reliable escort with convincing proof and signed letter from parents only will be permitted to receive the child for vacation.</li>
<li>Parents must not insist on sanctioning of leave for marriage of relative, family tour or party during the examination</li>
</ul><br></div><br><br>
</center>
</div>
</body>
</html>












